packages:
  - .

allowBuilds:
  esbuild: false
  sharp: false
  unrs-resolver: false
  workerd: false

blockExoticSubdeps: true

minimumReleaseAge: 10080 # 7 days in minutes

overrides:
  chokidar: '>=5'
  semver: '>=7'

trustPolicy: no-downgrade
