name: CI and Preview

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-26.04-arm
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install pnpm
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          install: false

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Prepare build
        env:
          VITE_SUPABASE_URL: ${{ vars.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: |
          touch .env.local
          echo "VITE_SUPABASE_URL=${VITE_SUPABASE_URL}" >> .env.local
          echo "VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}" >> .env.local

      - name: lint
        run: pnpm lint

      - name: Build
        run: pnpm build
